services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - rag-net

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"  # Expose API to host
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: >
      sh -c "
        ollama serve &
        sleep 5 &&
        ollama pull nomic-embed-text:v1.5 &&
        wait
      "
    networks:
      - rag-net
    
  rag-be:
    build:
      context: ./rag-be
      dockerfile: Dockerfile
    container_name: rag-be
    environment:
      - OLLAMA_URL=http://ollama:11434
      - QDRANT_URL=http://qdrant:6333
      - OPENAI_API_KEY=your_api_key_here
    ports:
      - "3001:3001"
    depends_on:
      - qdrant
      - ollama
    networks:
      - rag-net

  rag-fe:
    build:
      context: ./rag-fe
      dockerfile: Dockerfile
    container_name: rag-fe
    environment:
      - NEXT_PUBLIC_RAG_BE_URL=http://rag-be:3001
    ports:
      - "3000:3000"
    networks:
      - rag-net
    depends_on:
      - rag-be
      - qdrant
      - ollama

volumes:
  qdrant_data: 
  ollama_data:

networks:
  rag-net:
    driver: bridge
